// generate entitlement.pb.go when you change the protocol
// protoc entitlement.proto --go_out=plugins=grpc

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: entitlement.proto

package entitlement

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntitlementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action     string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	LabelValue string `protobuf:"bytes,2,opt,name=labelValue,proto3" json:"labelValue,omitempty"`
	UserID     string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *EntitlementRequest) Reset() {
	*x = EntitlementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entitlement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntitlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitlementRequest) ProtoMessage() {}

func (x *EntitlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entitlement_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitlementRequest.ProtoReflect.Descriptor instead.
func (*EntitlementRequest) Descriptor() ([]byte, []int) {
	return file_entitlement_proto_rawDescGZIP(), []int{0}
}

func (x *EntitlementRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EntitlementRequest) GetLabelValue() string {
	if x != nil {
		return x.LabelValue
	}
	return ""
}

func (x *EntitlementRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type EntitlementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entitled bool `protobuf:"varint,1,opt,name=entitled,proto3" json:"entitled,omitempty"`
}

func (x *EntitlementResponse) Reset() {
	*x = EntitlementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entitlement_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntitlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitlementResponse) ProtoMessage() {}

func (x *EntitlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entitlement_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitlementResponse.ProtoReflect.Descriptor instead.
func (*EntitlementResponse) Descriptor() ([]byte, []int) {
	return file_entitlement_proto_rawDescGZIP(), []int{1}
}

func (x *EntitlementResponse) GetEntitled() bool {
	if x != nil {
		return x.Entitled
	}
	return false
}

var File_entitlement_proto protoreflect.FileDescriptor

var file_entitlement_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0x64, 0x0a, 0x12, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e,
	0x0a, 0x0a, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x31, 0x0a, 0x13, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x64, 0x32, 0x5c, 0x0a, 0x0b, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x4d, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x64, 0x12, 0x1f, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61, 0x2f, 0x6c, 0x6f,
	0x6b, 0x69, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entitlement_proto_rawDescOnce sync.Once
	file_entitlement_proto_rawDescData = file_entitlement_proto_rawDesc
)

func file_entitlement_proto_rawDescGZIP() []byte {
	file_entitlement_proto_rawDescOnce.Do(func() {
		file_entitlement_proto_rawDescData = protoimpl.X.CompressGZIP(file_entitlement_proto_rawDescData)
	})
	return file_entitlement_proto_rawDescData
}

var file_entitlement_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_entitlement_proto_goTypes = []interface{}{
	(*EntitlementRequest)(nil),  // 0: entitlement.EntitlementRequest
	(*EntitlementResponse)(nil), // 1: entitlement.EntitlementResponse
}
var file_entitlement_proto_depIdxs = []int32{
	0, // 0: entitlement.Entitlement.Entitled:input_type -> entitlement.EntitlementRequest
	1, // 1: entitlement.Entitlement.Entitled:output_type -> entitlement.EntitlementResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entitlement_proto_init() }
func file_entitlement_proto_init() {
	if File_entitlement_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entitlement_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntitlementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entitlement_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntitlementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entitlement_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entitlement_proto_goTypes,
		DependencyIndexes: file_entitlement_proto_depIdxs,
		MessageInfos:      file_entitlement_proto_msgTypes,
	}.Build()
	File_entitlement_proto = out.File
	file_entitlement_proto_rawDesc = nil
	file_entitlement_proto_goTypes = nil
	file_entitlement_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EntitlementClient is the client API for Entitlement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EntitlementClient interface {
	Entitled(ctx context.Context, in *EntitlementRequest, opts ...grpc.CallOption) (*EntitlementResponse, error)
}

type entitlementClient struct {
	cc grpc.ClientConnInterface
}

func NewEntitlementClient(cc grpc.ClientConnInterface) EntitlementClient {
	return &entitlementClient{cc}
}

func (c *entitlementClient) Entitled(ctx context.Context, in *EntitlementRequest, opts ...grpc.CallOption) (*EntitlementResponse, error) {
	out := new(EntitlementResponse)
	err := c.cc.Invoke(ctx, "/entitlement.Entitlement/Entitled", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntitlementServer is the server API for Entitlement service.
type EntitlementServer interface {
	Entitled(context.Context, *EntitlementRequest) (*EntitlementResponse, error)
}

// UnimplementedEntitlementServer can be embedded to have forward compatible implementations.
type UnimplementedEntitlementServer struct {
}

func (*UnimplementedEntitlementServer) Entitled(context.Context, *EntitlementRequest) (*EntitlementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Entitled not implemented")
}

func RegisterEntitlementServer(s *grpc.Server, srv EntitlementServer) {
	s.RegisterService(&_Entitlement_serviceDesc, srv)
}

func _Entitlement_Entitled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntitlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServer).Entitled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.Entitlement/Entitled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServer).Entitled(ctx, req.(*EntitlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Entitlement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "entitlement.Entitlement",
	HandlerType: (*EntitlementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Entitled",
			Handler:    _Entitlement_Entitled_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entitlement.proto",
}
